In [4]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
df = pd.read_csv('...')
WhiteTimes = df['WhiteTimes'].apply(eval)
SumW = []
for i in range(len(WhiteTimes)):
    total_sum = sum(WhiteTimes[i])
    SumW.append(total_sum)

BlackTimes = df['BlackTimes'].apply(eval)
SumB = []
for i in range(len(BlackTimes)):
    total_sum = sum(BlackTimes[i])
    SumB.append(total_sum)
gamelenarray = np.array(SumW)+np.array(SumB)
name = ['Gamelength']
gamelen = pd.DataFrame(gamelenarray,columns =name)

EloDifference = df['WhiteElo'] - df['BlackElo']
name = ['EloDifference']
Elodif = pd.DataFrame(EloDifference,columns =name)

result = df['Result']
resultnames = np.unique(result)
resultDict=dict(zip(resultnames,range(len(resultnames)))) 
resultarray = np.array([resultDict[cl] for cl in result]) 
name = ['Result'] 
Result = pd.DataFrame(resultarray,columns =name) 

dfin = df[['WhiteElo', 'BlackElo','Middlegame', 'Endgame']] 
df = pd.concat([dfin, gamelen,Result,Elodif], axis=1)

,WhiteElo,BlackElo,Middlegame,Endgame,Gamelength,Result,EloDifference
0,1661,1640,21,50,410,2,21
1,1741,1734,19,77,760,1,7
2,1844,1794,20,41,320,0,50
3,1594,2028,24,53,227,0,-434
4,1652,1650,25,38,410,1,2
...,...,...,...,...,...,...,...
378,1675,1519,-1,-1,97,0,156
379,1521,1607,26,-1,217,2,-86
380,1992,1387,31,53,318,1,605
381,1791,1342,21,-1,419,1,449
382,1774,1748,13,37,396,0,26